export const FETCH_JOBS_SUCCESS = "FETCH_JOBS_SUCCESS";
export const FETCH_JOBS_FAILURE = "FETCH_JOBS_FAILURE"
export const FETCH_JOBS_BASED_ON_FILTER_SUCCESS = "FETCH_JOBS_BASED_ON_FILTER_SUCCESS"
export const FETCH_JOBS_BASED_ON_FILTER_FAILURE = "FETCH_JOBS_BASED_ON_FILTER_FAILURE"